### ISSUE TITLE
Is Medusa obsolete software?

### ISSUE THREAD

**Issue by jeffkimbrel** [gregmedlock/Medusa#103]
I have been trying to run the example Medusa jupyter notebooks, but it appears there have been many underlying changes to cobrapy that Medusa hasn't been updated for. Additionally, there have been no updates (or even new issues) in a long while.

We are about to start a new project that incorporates Medusa to handle the ensemble models. Is the code still being worked on? Is it getting rolled into cobrapy or another opencobra package? 

Thanks for your help.

Jeff

**Comment by gregmedlock** [comment]
Hi Jeff -- I am not actively working on Medusa right now (I shut down my lab). My plan has been to update it when cobrapy v1.0 is released, rather than updating with every stable cobrapy release. Medusa should still work with older cobrapy versions (I can update the requirements file to force use of a known, compatible version of cobrapy).

That said, I don't think there would be a ton of effort required to get Medusa operational with the latest stable release of cobrapy if there is a major need like what you've described. I'll do some assessment and let you know how long it may take.

**Comment by jeffkimbrel** [comment]
Thanks so much, Greg. I appreciate the response. Looking at the `requirements.txt` file in the repo, I can probably make a python environment using those specific versions of cobrapy, etc. to get a better feel for the medusa package. There is likely no need to make Medusa operational before the v1.0 cobrapy release if I can get an environment working.

Thanks again for the reply!

**Comment by gregmedlock** [comment]
I'd really appreciate it if you shared any thoughts on usability, design, etc. after you give it a try (regardless of whether you stick with it or decide to build something else from the ground up). Thanks!
